# Generated by Django 5.2 on 2025-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('service', models.CharField(choices=[('daily-clean', 'Ежедневная уборка'), ('deep-clean', 'Глубокая уборка'), ('window-clean', 'Мытье окон'), ('carpet-clean', 'Химчистка ковров'), ('disinfection', 'Дезинфекция помещений'), ('furniture-car', 'Уход за мебелью')], max_length=20, verbose_name='Услуга')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('role', models.CharField(max_length=30, verbose_name='Роль')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
            },
        ),
    ]
